### ISSUE TITLE
Is it possible to sign a message (not a transaction)

### ISSUE THREAD

**Issue by israelidanny** [phantom-labs/docs#3]
With `sol-wallet-adapter` it is possible to sign a message as a proof of account ownership. This is useful for all sorts of things - a couple of projects used it for wallet verification for airdrops. 

I don't see this documented anywhere for Phantom. Is this an existing feature? And if not, was it removed due to any specific reason?

**Comment by fragosti** [comment]
@israelidanny it was never added, but it is on our roadmap.
