### ISSUE TITLE
sendTransaction Transaction Message Mutated

### ISSUE THREAD

**Issue by Antttezy** [phantom-labs/docs#31]
Appears only if using phantom wallet adapter `sendTransaction` method, if use `signMessage` and then send using `connection.sendRawTransaction`, everything is ok
![image](https://user-images.githubusercontent.com/66439483/167716401-cc9dbd06-8a60-4723-8d90-d2322ef3f597.png)

**Comment by bfriel** [comment]
Hi @Antttezy thanks for the report. We pushed a fix for this earlier today. The fix is now out on Firefox and pending approval on Chrome.
