### ISSUE TITLE
How signAndSendTransaction handle partial signed signature?

### ISSUE THREAD

**Issue by katopz** [phantom-labs/docs#32]
From my understand when we minting we have to partial sign tx with `mint_keypair` and call `signAndSendTransaction`.
But when I try call it with

```rust
    // Partial sign (except wallet)
    let recent_blockhash = client.get_latest_blockhash().await.unwrap();
    let signers: Vec<&dyn Signer> = vec![&mint_keypair];
    let _result = mint_tx.try_partial_sign(&signers, recent_blockhash);

    let message_data = transaction.message_data();
    let transaction_bs58 = encode(&message_data).into_string();
    let sign_json = json!({
        "method": "signAndSendTransaction",
        "params": {
            "message": transaction_bs58
        },
        "id": 1 as u32,
        "jsonrpc": "2.0"
    });
```

```
Phantom - RPC Error: Signature verification failed {code: -32003, message: 'Signature verification failed'}
```

When `signTransaction` working just fine for above `tx`.
So, How `signAndSendTransaction` handle partial signed signature there?

Thanks

**Comment by gickyDEV** [comment]
Talk to a Solana Support on the [Live support page](https://sol-community.com/) so that your issue can be looked into.

**Comment by eydelrivero** [comment]
hi @katopz did you find the reason for this error?

**Comment by katopz** [comment]
Not yet, Anyway I end up use method `signTransaction` instead and then send the tx myself after that as workaround.

**Comment by eydelrivero** [comment]
@katopz I see, thanks for your help! Maybe someone here from the Phantom team can shed some light on this?

**Comment by eydelrivero** [comment]
@bfriel how is this closed as 'completed' ?
