### ISSUE TITLE
Open Browse Deeplink in In-App Browser on Initial Load

### ISSUE THREAD

**Issue by RyanTimesTen** [phantom-labs/docs#34]
Hello 👋 

As this is the docs site, I'm not sure if this is the correct place for this issue, so let me know if there's a better one!

I'm following the [browse](https://docs.phantom.app/integrating/deeplinks-ios-and-android/other-methods/browse) documentation to deeplink users into the Phantom in-app browser.

**Expected Behavior**

* users should be taken to the Phantom in-app browser on initial load of the Phantom app

**Actual behavior**

* users are not taken to the Phantom in-app browser on initial load. users have to go back to the original app, click the button again, and then the Phantom in-app browser loads

Reproduction: https://codesandbox.io/s/jovial-pascal-8gymif?file=/src/App.js

Steps to reproduce:
1. Make sure the Phantom app on your phone is killed
2. Open https://8gymif.csb.app/ on a mobile browser
3. Click "Connect with Phantom"
4. Observe the Phantom app loading, but staying on the home screen and not opening the in-app browser
5. Return to https://8gymif.csb.app/
6. Click "Connect with Phantom"
7. Now the Phantom in-app browser loads

Please let me know if I'm missing anything to make this work as expected, thanks!

**Comment by bfriel** [comment]
Hi @RyanTimesTen thanks for reaching out. This is a known issue that we have fixed but is still pending release via the App Store. It will be released as soon as it is approved.
