### ISSUE TITLE
PHANTOM DEBUG: Sent message to extension 

### ISSUE THREAD

**Issue by altyni86** [phantom-labs/docs#43]
I am receiving this log message from Phantom extension when visiting web3 apps (e.g. Uniswap). 
Log messages are flooding browser console at a rate of 100/1 minute.

**Comment by bamnenim-kryptonium** [comment]
This should be fixed ASAP. So annoying.

**Comment by toshvelaga** [comment]
Any progress on this? Would love to get rid of all these messages so it's easier to use the console to debug
<img width="737" alt="Screen Shot 2022-11-23 at 7 00 08 PM" src="https://user-images.githubusercontent.com/38474161/203677309-bb50470c-650c-4de8-82cf-cce6f9612e27.png">

**Comment by bfriel** [comment]
This has been fixed in Phantom `22.11.14`
