### ISSUE TITLE
connect method callback

### ISSUE THREAD

**Issue by ptorrent** [phantom-labs/docs#8]
Hi there,

Is there a way to know if user refuse to connect ?

```
	var provider = window.solana
	await ??? provider.connect({ onlyIfTrusted: false });
```

I tried this without success

```
	var result = await window.solana.request({
					method: "connect",
					params: {
						onlyIfTrusted: false 
					}
				})
```

other example:
![image](https://user-images.githubusercontent.com/6083644/132726933-4934bee3-1799-43be-9828-a9d60df7066b.png)

my console.log or console.error never fire

Thanks for your help

**Comment by mim-Armand** [comment]
You can check if a user's wallet is connected at any time through `window.solana?.isConnected`, it will return `true` if connected and `false` otherwise.

**Comment by fragosti** [comment]
We have made this API cleaner recently https://docs.phantom.app/integrating/establishing-a-connection#connecting
